### ISSUE TITLE
argon2 fails to install on OS X

### ISSUE THREAD

**Issue by bwesterb** [flamewow/argon2_py#3]
```
$ sudo pip -v install argon2
Collecting argon2
  Getting page https://pypi.python.org/simple/argon2/
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/argon2/ HTTP/1.1" 200 240
  1 location(s) to search for versions of argon2:
  * https://pypi.python.org/simple/argon2/
  Getting page https://pypi.python.org/simple/argon2/
  "GET /simple/argon2/ HTTP/1.1" 200 240
  Analyzing links from page https://pypi.python.org/simple/argon2/
    Found link https://pypi.python.org/packages/source/a/argon2/argon2-0.1.8.tar.gz#md5=bc7a7f3af5ec0222ba4cb95d142e2a3f (from https://pypi.python.org/simple/argon2/), version: 0.1.8
    Found link https://pypi.python.org/packages/source/a/argon2/argon2-0.1.9.tar.gz#md5=8cafb4fe1e9525e695e5489c63492f95 (from https://pypi.python.org/simple/argon2/), version: 0.1.9
  Using version 0.1.9 (newest of versions: 0.1.9, 0.1.8)
  "GET /packages/source/a/argon2/argon2-0.1.9.tar.gz HTTP/1.1" 200 28256
  Downloading argon2-0.1.9.tar.gz
  Downloading from URL https://pypi.python.org/packages/source/a/argon2/argon2-0.1.9.tar.gz#md5=8cafb4fe1e9525e695e5489c63492f95 (from https://pypi.python.org/simple/argon2/)
  Running setup.py (path:/private/tmp/pip-build-Wo99ke/argon2/setup.py) egg_info for package argon2
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/argon2.egg-info
    writing pip-egg-info/argon2.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/argon2.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/argon2.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/argon2.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    package init file 'phc-winner-argon2/__init__.py' not found (or not a regular file)
    reading manifest file 'pip-egg-info/argon2.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/argon2.egg-info/SOURCES.txt'
  Source in /private/tmp/pip-build-Wo99ke/argon2 has version 0.1.9, which satisfies requirement argon2 from https://pypi.python.org/packages/source/a/argon2/argon2-0.1.9.tar.gz#md5=8cafb4fe1e9525e695e5489c63492f95
Installing collected packages: argon2
  Running setup.py install for argon2
    Running command /opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-Wo99ke/argon2/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Gv3uNh-record/install-record.txt --single-version-externally-managed --compile
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.11-x86_64-2.7
    copying argon2.py -> build/lib.macosx-10.11-x86_64-2.7
    package init file 'phc-winner-argon2/__init__.py' not found (or not a regular file)
    running build_ext
    building '_argon2' extension
    creating build/temp.macosx-10.11-x86_64-2.7
    creating build/temp.macosx-10.11-x86_64-2.7/src
    creating build/temp.macosx-10.11-x86_64-2.7/phc-winner-argon2
    creating build/temp.macosx-10.11-x86_64-2.7/phc-winner-argon2/src
    creating build/temp.macosx-10.11-x86_64-2.7/phc-winner-argon2/src/blake2
    /usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DHAVE_CONFIG_H -DHAVE_SYSCTL_HW_USERMEM=1 -I./phc-winner-argon2 -I./phc-winner-argon2/src -I./phc-winner-argon2/src/blake2 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c ./src/argon2_py.c -o build/temp.macosx-10.11-x86_64-2.7/./src/argon2_py.o
    /usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DHAVE_CONFIG_H -DHAVE_SYSCTL_HW_USERMEM=1 -I./phc-winner-argon2 -I./phc-winner-argon2/src -I./phc-winner-argon2/src/blake2 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c ./phc-winner-argon2/src/argon2.c -o build/temp.macosx-10.11-x86_64-2.7/./phc-winner-argon2/src/argon2.o
    /usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DHAVE_CONFIG_H -DHAVE_SYSCTL_HW_USERMEM=1 -I./phc-winner-argon2 -I./phc-winner-argon2/src -I./phc-winner-argon2/src/blake2 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c ./phc-winner-argon2/src/core.c -o build/temp.macosx-10.11-x86_64-2.7/./phc-winner-argon2/src/core.o
    /usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DHAVE_CONFIG_H -DHAVE_SYSCTL_HW_USERMEM=1 -I./phc-winner-argon2 -I./phc-winner-argon2/src -I./phc-winner-argon2/src/blake2 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c ./phc-winner-argon2/src/encoding.c -o build/temp.macosx-10.11-x86_64-2.7/./phc-winner-argon2/src/encoding.o
    /usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DHAVE_CONFIG_H -DHAVE_SYSCTL_HW_USERMEM=1 -I./phc-winner-argon2 -I./phc-winner-argon2/src -I./phc-winner-argon2/src/blake2 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c ./phc-winner-argon2/src/ref.c -o build/temp.macosx-10.11-x86_64-2.7/./phc-winner-argon2/src/ref.o
    /usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DHAVE_CONFIG_H -DHAVE_SYSCTL_HW_USERMEM=1 -I./phc-winner-argon2 -I./phc-winner-argon2/src -I./phc-winner-argon2/src/blake2 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c ./phc-winner-argon2/src/thread.c -o build/temp.macosx-10.11-x86_64-2.7/./phc-winner-argon2/src/thread.o
    /usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DHAVE_CONFIG_H -DHAVE_SYSCTL_HW_USERMEM=1 -I./phc-winner-argon2 -I./phc-winner-argon2/src -I./phc-winner-argon2/src/blake2 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c ./phc-winner-argon2/src/blake2/blake2b.c -o build/temp.macosx-10.11-x86_64-2.7/./phc-winner-argon2/src/blake2/blake2b.o
    /usr/bin/clang -bundle -undefined dynamic_lookup -L/opt/local/lib -Wl,-headerpad_max_install_names -L/opt/local/lib/db48 build/temp.macosx-10.11-x86_64-2.7/./src/argon2_py.o build/temp.macosx-10.11-x86_64-2.7/./phc-winner-argon2/src/argon2.o build/temp.macosx-10.11-x86_64-2.7/./phc-winner-argon2/src/core.o build/temp.macosx-10.11-x86_64-2.7/./phc-winner-argon2/src/encoding.o build/temp.macosx-10.11-x86_64-2.7/./phc-winner-argon2/src/ref.o build/temp.macosx-10.11-x86_64-2.7/./phc-winner-argon2/src/thread.o build/temp.macosx-10.11-x86_64-2.7/./phc-winner-argon2/src/blake2/blake2b.o -lc_argon2 -o build/lib.macosx-10.11-x86_64-2.7/_argon2.so
    ld: library not found for -lc_argon2
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command '/usr/bin/clang' failed with exit status 1
    Complete output from command /opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-Wo99ke/argon2/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Gv3uNh-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.11-x86_64-2.7
    copying argon2.py -> build/lib.macosx-10.11-x86_64-2.7
    package init file 'phc-winner-argon2/__init__.py' not found (or not a regular file)
    running build_ext
    building '_argon2' extension
    creating build/temp.macosx-10.11-x86_64-2.7
    creating build/temp.macosx-10.11-x86_64-2.7/src
    creating build/temp.macosx-10.11-x86_64-2.7/phc-winner-argon2
    creating build/temp.macosx-10.11-x86_64-2.7/phc-winner-argon2/src
    creating build/temp.macosx-10.11-x86_64-2.7/phc-winner-argon2/src/blake2
    /usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DHAVE_CONFIG_H -DHAVE_SYSCTL_HW_USERMEM=1 -I./phc-winner-argon2 -I./phc-winner-argon2/src -I./phc-winner-argon2/src/blake2 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c ./src/argon2_py.c -o build/temp.macosx-10.11-x86_64-2.7/./src/argon2_py.o
    /usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DHAVE_CONFIG_H -DHAVE_SYSCTL_HW_USERMEM=1 -I./phc-winner-argon2 -I./phc-winner-argon2/src -I./phc-winner-argon2/src/blake2 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c ./phc-winner-argon2/src/argon2.c -o build/temp.macosx-10.11-x86_64-2.7/./phc-winner-argon2/src/argon2.o
    /usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DHAVE_CONFIG_H -DHAVE_SYSCTL_HW_USERMEM=1 -I./phc-winner-argon2 -I./phc-winner-argon2/src -I./phc-winner-argon2/src/blake2 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c ./phc-winner-argon2/src/core.c -o build/temp.macosx-10.11-x86_64-2.7/./phc-winner-argon2/src/core.o
    /usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DHAVE_CONFIG_H -DHAVE_SYSCTL_HW_USERMEM=1 -I./phc-winner-argon2 -I./phc-winner-argon2/src -I./phc-winner-argon2/src/blake2 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c ./phc-winner-argon2/src/encoding.c -o build/temp.macosx-10.11-x86_64-2.7/./phc-winner-argon2/src/encoding.o
    /usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DHAVE_CONFIG_H -DHAVE_SYSCTL_HW_USERMEM=1 -I./phc-winner-argon2 -I./phc-winner-argon2/src -I./phc-winner-argon2/src/blake2 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c ./phc-winner-argon2/src/ref.c -o build/temp.macosx-10.11-x86_64-2.7/./phc-winner-argon2/src/ref.o
    /usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DHAVE_CONFIG_H -DHAVE_SYSCTL_HW_USERMEM=1 -I./phc-winner-argon2 -I./phc-winner-argon2/src -I./phc-winner-argon2/src/blake2 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c ./phc-winner-argon2/src/thread.c -o build/temp.macosx-10.11-x86_64-2.7/./phc-winner-argon2/src/thread.o
    /usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DHAVE_CONFIG_H -DHAVE_SYSCTL_HW_USERMEM=1 -I./phc-winner-argon2 -I./phc-winner-argon2/src -I./phc-winner-argon2/src/blake2 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c ./phc-winner-argon2/src/blake2/blake2b.c -o build/temp.macosx-10.11-x86_64-2.7/./phc-winner-argon2/src/blake2/blake2b.o
    /usr/bin/clang -bundle -undefined dynamic_lookup -L/opt/local/lib -Wl,-headerpad_max_install_names -L/opt/local/lib/db48 build/temp.macosx-10.11-x86_64-2.7/./src/argon2_py.o build/temp.macosx-10.11-x86_64-2.7/./phc-winner-argon2/src/argon2.o build/temp.macosx-10.11-x86_64-2.7/./phc-winner-argon2/src/core.o build/temp.macosx-10.11-x86_64-2.7/./phc-winner-argon2/src/encoding.o build/temp.macosx-10.11-x86_64-2.7/./phc-winner-argon2/src/ref.o build/temp.macosx-10.11-x86_64-2.7/./phc-winner-argon2/src/thread.o build/temp.macosx-10.11-x86_64-2.7/./phc-winner-argon2/src/blake2/blake2b.o -lc_argon2 -o build/lib.macosx-10.11-x86_64-2.7/_argon2.so
    ld: library not found for -lc_argon2
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command '/usr/bin/clang' failed with exit status 1

    ----------------------------------------
Cleaning up...
  Removing source in /private/tmp/pip-build-Wo99ke/argon2
Command "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-Wo99ke/argon2/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Gv3uNh-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-Wo99ke/argon2
Exception information:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/req/req_set.py", line 646, in install
    **kwargs
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/req/req_install.py", line 852, in install
    show_stdout=False,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/utils/__init__.py", line 733, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-Wo99ke/argon2/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Gv3uNh-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-Wo99ke/argon2
Starting new HTTPS connection (1): pypi.python.org
"GET /pypi/pip/json HTTP/1.1" 200 46057
```

**Comment by flamewow** [comment]
Fixed, try new version

**Comment by bwesterb** [comment]
It's fixed.  Thanks.
